/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSectionResponseFromDiscriminatorValue, serializeBulkUpdateSectionDisplayOrderRequest, serializeSectionResponse, type BulkUpdateSectionDisplayOrderRequest, type SectionResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/practice-plans/{key-id}/sections/order
 */
export interface OrderRequestBuilder extends BaseRequestBuilder<OrderRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SectionResponse[]>}
     */
     put(body: BulkUpdateSectionDisplayOrderRequest[], requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SectionResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: BulkUpdateSectionDisplayOrderRequest[], requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrderRequestBuilderUriTemplate = "{+baseurl}/api/practice-plans/{key%2Did}/sections/order";
/**
 * Metadata for all the requests in the request builder.
 */
export const OrderRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: OrderRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBulkUpdateSectionDisplayOrderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
