/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPlanDrillResponseFromDiscriminatorValue, serializeCreatePlanDrillRequest, serializePlanDrillResponse, type CreatePlanDrillRequest, type PlanDrillResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithDrillKeyItemRequestBuilder, WithDrillKeyItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/practice-plans/{key-id}/sections/{sectionKey}/plan-drills
 */
export interface PlanDrillsRequestBuilder extends BaseRequestBuilder<PlanDrillsRequestBuilder> {
    /**
     * Gets an item from the GamePlanPro.Api.api.practicePlans.item.sections.item.planDrills.item collection
     * @param drillKey Unique identifier of the item
     * @returns {WithDrillKeyItemRequestBuilder}
     */
     byDrillKey(drillKey: Guid) : WithDrillKeyItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PlanDrillResponse>}
     */
     post(body: CreatePlanDrillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PlanDrillResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePlanDrillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlanDrillsRequestBuilderUriTemplate = "{+baseurl}/api/practice-plans/{key%2Did}/sections/{sectionKey}/plan-drills";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PlanDrillsRequestBuilderNavigationMetadata: Record<Exclude<keyof PlanDrillsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDrillKey: {
        requestsMetadata: WithDrillKeyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["drillKey"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PlanDrillsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PlanDrillsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPlanDrillResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePlanDrillRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
