/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSectionResponseFromDiscriminatorValue, serializeSectionResponse, serializeUpdateSectionRequest, type SectionResponse, type UpdateSectionRequest } from '../../../../../models/index.js';
// @ts-ignore
import { PlanDrillsRequestBuilderNavigationMetadata, PlanDrillsRequestBuilderRequestsMetadata, type PlanDrillsRequestBuilder } from './planDrills/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/practice-plans/{key-id}/sections/{sectionKey}
 */
export interface WithSectionKeyItemRequestBuilder extends BaseRequestBuilder<WithSectionKeyItemRequestBuilder> {
    /**
     * The planDrills property
     */
    get planDrills(): PlanDrillsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SectionResponse>}
     */
     put(body: UpdateSectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SectionResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateSectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithSectionKeyItemRequestBuilderUriTemplate = "{+baseurl}/api/practice-plans/{key%2Did}/sections/{sectionKey}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSectionKeyItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSectionKeyItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    planDrills: {
        requestsMetadata: PlanDrillsRequestBuilderRequestsMetadata,
        navigationMetadata: PlanDrillsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSectionKeyItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithSectionKeyItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    put: {
        uriTemplate: WithSectionKeyItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateSectionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
