/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSectionResponseFromDiscriminatorValue, serializeCreateSectionRequest, serializeSectionResponse, type CreateSectionRequest, type SectionResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithSectionKeyItemRequestBuilder, WithSectionKeyItemRequestBuilderNavigationMetadata, WithSectionKeyItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/practice-plans/{key-id}/sections
 */
export interface SectionsRequestBuilder extends BaseRequestBuilder<SectionsRequestBuilder> {
    /**
     * Gets an item from the GamePlanPro.Api.api.practicePlans.item.sections.item collection
     * @param sectionKey Unique identifier of the item
     * @returns {WithSectionKeyItemRequestBuilder}
     */
     bySectionKey(sectionKey: Guid) : WithSectionKeyItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SectionResponse>}
     */
     post(body: CreateSectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SectionResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateSectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SectionsRequestBuilderUriTemplate = "{+baseurl}/api/practice-plans/{key%2Did}/sections";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySectionKey: {
        requestsMetadata: WithSectionKeyItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithSectionKeyItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["sectionKey"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SectionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SectionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateSectionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
