/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDrillTypeResponseFromDiscriminatorValue, type DrillTypeResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/drill-types
 */
export interface DrillTypesRequestBuilder extends BaseRequestBuilder<DrillTypesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DrillTypeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DrillTypeResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DrillTypesRequestBuilderUriTemplate = "{+baseurl}/api/drill-types";
/**
 * Metadata for all the requests in the request builder.
 */
export const DrillTypesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DrillTypesRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDrillTypeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
