/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ByTeamRequestBuilderRequestsMetadata, type ByTeamRequestBuilder } from './byTeam/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/coaches
 */
export interface CoachesRequestBuilder extends BaseRequestBuilder<CoachesRequestBuilder> {
    /**
     * The byTeam property
     */
    get byTeam(): ByTeamRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CoachesRequestBuilderUriTemplate = "{+baseurl}/api/coaches";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CoachesRequestBuilderNavigationMetadata: Record<Exclude<keyof CoachesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeam: {
        requestsMetadata: ByTeamRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
