/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index.js';
// @ts-ignore
import { CoachesRequestBuilderNavigationMetadata, type CoachesRequestBuilder } from './coaches/index.js';
// @ts-ignore
import { DrillsRequestBuilderNavigationMetadata, DrillsRequestBuilderRequestsMetadata, type DrillsRequestBuilder } from './drills/index.js';
// @ts-ignore
import { DrillTypesRequestBuilderRequestsMetadata, type DrillTypesRequestBuilder } from './drillTypes/index.js';
// @ts-ignore
import { PracticePlansRequestBuilderNavigationMetadata, PracticePlansRequestBuilderRequestsMetadata, type PracticePlansRequestBuilder } from './practicePlans/index.js';
// @ts-ignore
import { TeamRequestBuilderRequestsMetadata, type TeamRequestBuilder } from './team/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The coaches property
     */
    get coaches(): CoachesRequestBuilder;
    /**
     * The drills property
     */
    get drills(): DrillsRequestBuilder;
    /**
     * The drillTypes property
     */
    get drillTypes(): DrillTypesRequestBuilder;
    /**
     * The practicePlans property
     */
    get practicePlans(): PracticePlansRequestBuilder;
    /**
     * The team property
     */
    get team(): TeamRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    coaches: {
        navigationMetadata: CoachesRequestBuilderNavigationMetadata,
    },
    drills: {
        requestsMetadata: DrillsRequestBuilderRequestsMetadata,
        navigationMetadata: DrillsRequestBuilderNavigationMetadata,
    },
    drillTypes: {
        requestsMetadata: DrillTypesRequestBuilderRequestsMetadata,
    },
    practicePlans: {
        requestsMetadata: PracticePlansRequestBuilderRequestsMetadata,
        navigationMetadata: PracticePlansRequestBuilderNavigationMetadata,
    },
    team: {
        requestsMetadata: TeamRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
