/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDrillResponseFromDiscriminatorValue, serializeCreateDrillRequest, serializeDrillResponse, type CreateDrillRequest, type DrillResponse } from '../../models/index.js';
// @ts-ignore
import { type WithKeyItemRequestBuilder, WithKeyItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/drills
 */
export interface DrillsRequestBuilder extends BaseRequestBuilder<DrillsRequestBuilder> {
    /**
     * Gets an item from the GamePlanPro.Api.api.drills.item collection
     * @param key Unique identifier of the item
     * @returns {WithKeyItemRequestBuilder}
     */
     byKey(key: Guid) : WithKeyItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DrillResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<DrillsRequestBuilderGetQueryParameters> | undefined) : Promise<DrillResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DrillResponse>}
     */
     post(body: CreateDrillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DrillResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DrillsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateDrillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface DrillsRequestBuilderGetQueryParameters {
    drillTypeId?: number;
    source?: number;
}
/**
 * Uri template for the request builder.
 */
export const DrillsRequestBuilderUriTemplate = "{+baseurl}/api/drills{?drillTypeId*,source*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DrillsRequestBuilderNavigationMetadata: Record<Exclude<keyof DrillsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byKey: {
        requestsMetadata: WithKeyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["key"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DrillsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DrillsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDrillResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: DrillsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDrillResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateDrillRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
