/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AuthUserResponse extends Parsable {
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthUserResponse}
 */
// @ts-ignore
export function createAuthUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthUserResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterRequest}
 */
// @ts-ignore
export function createRegisterRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterRequest;
}
/**
 * The deserialization information for the current model
 * @param AuthUserResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthUserResponse(authUserResponse: Partial<AuthUserResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayName": n => { authUserResponse.displayName = n.getStringValue(); },
        "email": n => { authUserResponse.email = n.getStringValue(); },
        "id": n => { authUserResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterRequest(registerRequest: Partial<RegisterRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayName": n => { registerRequest.displayName = n.getStringValue(); },
        "email": n => { registerRequest.email = n.getStringValue(); },
        "password": n => { registerRequest.password = n.getStringValue(); },
    }
}
export interface LoginRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface RegisterRequest extends Parsable {
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
/**
 * Serializes information the current object
 * @param AuthUserResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthUserResponse(writer: SerializationWriter, authUserResponse: Partial<AuthUserResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authUserResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("displayName", authUserResponse.displayName);
    writer.writeStringValue("email", authUserResponse.email);
    writer.writeStringValue("id", authUserResponse.id);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginRequest.email);
    writer.writeStringValue("password", loginRequest.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterRequest(writer: SerializationWriter, registerRequest: Partial<RegisterRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("displayName", registerRequest.displayName);
    writer.writeStringValue("email", registerRequest.email);
    writer.writeStringValue("password", registerRequest.password);
}
/* tslint:enable */
/* eslint-enable */
