/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AuthUserResponse extends Parsable {
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: string | null;
}
export interface CoachRequest extends Parsable {
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CoachResponse extends Parsable {
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthUserResponse}
 */
// @ts-ignore
export function createAuthUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuthUserResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CoachRequest}
 */
// @ts-ignore
export function createCoachRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCoachRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CoachResponse}
 */
// @ts-ignore
export function createCoachResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCoachResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateDrillRequest}
 */
// @ts-ignore
export function createCreateDrillRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateDrillRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePlanDrillRequest}
 */
// @ts-ignore
export function createCreatePlanDrillRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePlanDrillRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePracticePlanRequest}
 */
// @ts-ignore
export function createCreatePracticePlanRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePracticePlanRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateSectionRequest}
 */
// @ts-ignore
export function createCreateSectionRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateSectionRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateTeamRequest}
 */
// @ts-ignore
export function createCreateTeamRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateTeamRequest;
}
export interface CreateDrillRequest extends Parsable {
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The drillTypeId property
     */
    drillTypeId?: number | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DrillResponse}
 */
// @ts-ignore
export function createDrillResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDrillResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DrillTypeResponse}
 */
// @ts-ignore
export function createDrillTypeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDrillTypeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
export interface CreatePlanDrillRequest extends Parsable {
    /**
     * The coachAssignment property
     */
    coachAssignment?: string | null;
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The drillTypeId property
     */
    drillTypeId?: number | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The playerCount property
     */
    playerCount?: number | null;
    /**
     * The sourceDrillKey property
     */
    sourceDrillKey?: Guid | null;
    /**
     * The stationGroup property
     */
    stationGroup?: Guid | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanDrillResponse}
 */
// @ts-ignore
export function createPlanDrillResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPlanDrillResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PracticePlanDetailResponse}
 */
// @ts-ignore
export function createPracticePlanDetailResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPracticePlanDetailResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PracticePlanListResponse}
 */
// @ts-ignore
export function createPracticePlanListResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPracticePlanListResponse;
}
export interface CreatePracticePlanRequest extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The intendedDuration property
     */
    intendedDuration?: number | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterRequest}
 */
// @ts-ignore
export function createRegisterRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterRequest;
}
export interface CreateSectionRequest extends Parsable {
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SectionResponse}
 */
// @ts-ignore
export function createSectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSectionResponse;
}
export interface CreateTeamRequest extends Parsable {
    /**
     * The coaches property
     */
    coaches?: CoachRequest[] | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TeamResponse}
 */
// @ts-ignore
export function createTeamResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTeamResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateDrillRequest}
 */
// @ts-ignore
export function createUpdateDrillRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateDrillRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdatePlanDrillRequest}
 */
// @ts-ignore
export function createUpdatePlanDrillRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdatePlanDrillRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdatePracticePlanRequest}
 */
// @ts-ignore
export function createUpdatePracticePlanRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdatePracticePlanRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateSectionRequest}
 */
// @ts-ignore
export function createUpdateSectionRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateSectionRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateTeamRequest}
 */
// @ts-ignore
export function createUpdateTeamRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateTeamRequest;
}
/**
 * The deserialization information for the current model
 * @param AuthUserResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthUserResponse(authUserResponse: Partial<AuthUserResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayName": n => { authUserResponse.displayName = n.getStringValue(); },
        "email": n => { authUserResponse.email = n.getStringValue(); },
        "id": n => { authUserResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CoachRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCoachRequest(coachRequest: Partial<CoachRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "key": n => { coachRequest.key = n.getGuidValue(); },
        "name": n => { coachRequest.name = n.getStringValue(); },
        "type": n => { coachRequest.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CoachResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCoachResponse(coachResponse: Partial<CoachResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "key": n => { coachResponse.key = n.getGuidValue(); },
        "name": n => { coachResponse.name = n.getStringValue(); },
        "type": n => { coachResponse.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateDrillRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateDrillRequest(createDrillRequest: Partial<CreateDrillRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "demoLink": n => { createDrillRequest.demoLink = n.getStringValue(); },
        "description": n => { createDrillRequest.description = n.getStringValue(); },
        "drillTypeId": n => { createDrillRequest.drillTypeId = n.getNumberValue(); },
        "duration": n => { createDrillRequest.duration = n.getNumberValue(); },
        "instructions": n => { createDrillRequest.instructions = n.getStringValue(); },
        "name": n => { createDrillRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePlanDrillRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePlanDrillRequest(createPlanDrillRequest: Partial<CreatePlanDrillRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coachAssignment": n => { createPlanDrillRequest.coachAssignment = n.getStringValue(); },
        "demoLink": n => { createPlanDrillRequest.demoLink = n.getStringValue(); },
        "displayOrder": n => { createPlanDrillRequest.displayOrder = n.getNumberValue(); },
        "drillTypeId": n => { createPlanDrillRequest.drillTypeId = n.getNumberValue(); },
        "duration": n => { createPlanDrillRequest.duration = n.getNumberValue(); },
        "instructions": n => { createPlanDrillRequest.instructions = n.getStringValue(); },
        "name": n => { createPlanDrillRequest.name = n.getStringValue(); },
        "playerCount": n => { createPlanDrillRequest.playerCount = n.getNumberValue(); },
        "sourceDrillKey": n => { createPlanDrillRequest.sourceDrillKey = n.getGuidValue(); },
        "stationGroup": n => { createPlanDrillRequest.stationGroup = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePracticePlanRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePracticePlanRequest(createPracticePlanRequest: Partial<CreatePracticePlanRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { createPracticePlanRequest.description = n.getStringValue(); },
        "intendedDuration": n => { createPracticePlanRequest.intendedDuration = n.getNumberValue(); },
        "location": n => { createPracticePlanRequest.location = n.getStringValue(); },
        "name": n => { createPracticePlanRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateSectionRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateSectionRequest(createSectionRequest: Partial<CreateSectionRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayOrder": n => { createSectionRequest.displayOrder = n.getNumberValue(); },
        "name": n => { createSectionRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateTeamRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateTeamRequest(createTeamRequest: Partial<CreateTeamRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coaches": n => { createTeamRequest.coaches = n.getCollectionOfObjectValues<CoachRequest>(createCoachRequestFromDiscriminatorValue); },
        "name": n => { createTeamRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DrillResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDrillResponse(drillResponse: Partial<DrillResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { drillResponse.createdAt = n.getDateValue(); },
        "demoLink": n => { drillResponse.demoLink = n.getStringValue(); },
        "description": n => { drillResponse.description = n.getStringValue(); },
        "drillType": n => { drillResponse.drillType = n.getObjectValue<DrillTypeResponse>(createDrillTypeResponseFromDiscriminatorValue); },
        "duration": n => { drillResponse.duration = n.getNumberValue(); },
        "instructions": n => { drillResponse.instructions = n.getStringValue(); },
        "key": n => { drillResponse.key = n.getGuidValue(); },
        "name": n => { drillResponse.name = n.getStringValue(); },
        "source": n => { drillResponse.source = n.getStringValue(); },
        "updatedAt": n => { drillResponse.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DrillTypeResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDrillTypeResponse(drillTypeResponse: Partial<DrillTypeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { drillTypeResponse.id = n.getNumberValue(); },
        "name": n => { drillTypeResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PlanDrillResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanDrillResponse(planDrillResponse: Partial<PlanDrillResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coachAssignment": n => { planDrillResponse.coachAssignment = n.getStringValue(); },
        "demoLink": n => { planDrillResponse.demoLink = n.getStringValue(); },
        "displayOrder": n => { planDrillResponse.displayOrder = n.getNumberValue(); },
        "drillType": n => { planDrillResponse.drillType = n.getObjectValue<DrillTypeResponse>(createDrillTypeResponseFromDiscriminatorValue); },
        "duration": n => { planDrillResponse.duration = n.getNumberValue(); },
        "instructions": n => { planDrillResponse.instructions = n.getStringValue(); },
        "key": n => { planDrillResponse.key = n.getGuidValue(); },
        "name": n => { planDrillResponse.name = n.getStringValue(); },
        "playerCount": n => { planDrillResponse.playerCount = n.getNumberValue(); },
        "sourceDrillKey": n => { planDrillResponse.sourceDrillKey = n.getGuidValue(); },
        "stationGroup": n => { planDrillResponse.stationGroup = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PracticePlanDetailResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPracticePlanDetailResponse(practicePlanDetailResponse: Partial<PracticePlanDetailResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { practicePlanDetailResponse.createdAt = n.getDateValue(); },
        "description": n => { practicePlanDetailResponse.description = n.getStringValue(); },
        "intendedDuration": n => { practicePlanDetailResponse.intendedDuration = n.getNumberValue(); },
        "key": n => { practicePlanDetailResponse.key = n.getGuidValue(); },
        "lastModifiedAt": n => { practicePlanDetailResponse.lastModifiedAt = n.getDateValue(); },
        "location": n => { practicePlanDetailResponse.location = n.getStringValue(); },
        "name": n => { practicePlanDetailResponse.name = n.getStringValue(); },
        "sections": n => { practicePlanDetailResponse.sections = n.getCollectionOfObjectValues<SectionResponse>(createSectionResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PracticePlanListResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPracticePlanListResponse(practicePlanListResponse: Partial<PracticePlanListResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { practicePlanListResponse.createdAt = n.getDateValue(); },
        "intendedDuration": n => { practicePlanListResponse.intendedDuration = n.getNumberValue(); },
        "key": n => { practicePlanListResponse.key = n.getGuidValue(); },
        "lastModifiedAt": n => { practicePlanListResponse.lastModifiedAt = n.getDateValue(); },
        "location": n => { practicePlanListResponse.location = n.getStringValue(); },
        "name": n => { practicePlanListResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterRequest(registerRequest: Partial<RegisterRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayName": n => { registerRequest.displayName = n.getStringValue(); },
        "email": n => { registerRequest.email = n.getStringValue(); },
        "password": n => { registerRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SectionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSectionResponse(sectionResponse: Partial<SectionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayOrder": n => { sectionResponse.displayOrder = n.getNumberValue(); },
        "key": n => { sectionResponse.key = n.getGuidValue(); },
        "name": n => { sectionResponse.name = n.getStringValue(); },
        "planDrills": n => { sectionResponse.planDrills = n.getCollectionOfObjectValues<PlanDrillResponse>(createPlanDrillResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param TeamResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTeamResponse(teamResponse: Partial<TeamResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coaches": n => { teamResponse.coaches = n.getCollectionOfObjectValues<CoachResponse>(createCoachResponseFromDiscriminatorValue); },
        "key": n => { teamResponse.key = n.getGuidValue(); },
        "name": n => { teamResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateDrillRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateDrillRequest(updateDrillRequest: Partial<UpdateDrillRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "demoLink": n => { updateDrillRequest.demoLink = n.getStringValue(); },
        "description": n => { updateDrillRequest.description = n.getStringValue(); },
        "drillTypeId": n => { updateDrillRequest.drillTypeId = n.getNumberValue(); },
        "duration": n => { updateDrillRequest.duration = n.getNumberValue(); },
        "instructions": n => { updateDrillRequest.instructions = n.getStringValue(); },
        "name": n => { updateDrillRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdatePlanDrillRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdatePlanDrillRequest(updatePlanDrillRequest: Partial<UpdatePlanDrillRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coachAssignment": n => { updatePlanDrillRequest.coachAssignment = n.getStringValue(); },
        "demoLink": n => { updatePlanDrillRequest.demoLink = n.getStringValue(); },
        "displayOrder": n => { updatePlanDrillRequest.displayOrder = n.getNumberValue(); },
        "drillTypeId": n => { updatePlanDrillRequest.drillTypeId = n.getNumberValue(); },
        "duration": n => { updatePlanDrillRequest.duration = n.getNumberValue(); },
        "instructions": n => { updatePlanDrillRequest.instructions = n.getStringValue(); },
        "name": n => { updatePlanDrillRequest.name = n.getStringValue(); },
        "playerCount": n => { updatePlanDrillRequest.playerCount = n.getNumberValue(); },
        "stationGroup": n => { updatePlanDrillRequest.stationGroup = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdatePracticePlanRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdatePracticePlanRequest(updatePracticePlanRequest: Partial<UpdatePracticePlanRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { updatePracticePlanRequest.description = n.getStringValue(); },
        "intendedDuration": n => { updatePracticePlanRequest.intendedDuration = n.getNumberValue(); },
        "location": n => { updatePracticePlanRequest.location = n.getStringValue(); },
        "name": n => { updatePracticePlanRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateSectionRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateSectionRequest(updateSectionRequest: Partial<UpdateSectionRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "displayOrder": n => { updateSectionRequest.displayOrder = n.getNumberValue(); },
        "name": n => { updateSectionRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateTeamRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateTeamRequest(updateTeamRequest: Partial<UpdateTeamRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "coaches": n => { updateTeamRequest.coaches = n.getCollectionOfObjectValues<CoachRequest>(createCoachRequestFromDiscriminatorValue); },
        "name": n => { updateTeamRequest.name = n.getStringValue(); },
    }
}
export interface DrillResponse extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The drillType property
     */
    drillType?: DrillTypeResponse | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The source property
     */
    source?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface DrillTypeResponse extends Parsable {
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface LoginRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface PlanDrillResponse extends Parsable {
    /**
     * The coachAssignment property
     */
    coachAssignment?: string | null;
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The drillType property
     */
    drillType?: DrillTypeResponse | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The playerCount property
     */
    playerCount?: number | null;
    /**
     * The sourceDrillKey property
     */
    sourceDrillKey?: Guid | null;
    /**
     * The stationGroup property
     */
    stationGroup?: Guid | null;
}
export interface PracticePlanDetailResponse extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The intendedDuration property
     */
    intendedDuration?: number | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The lastModifiedAt property
     */
    lastModifiedAt?: Date | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The sections property
     */
    sections?: SectionResponse[] | null;
}
export interface PracticePlanListResponse extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The intendedDuration property
     */
    intendedDuration?: number | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The lastModifiedAt property
     */
    lastModifiedAt?: Date | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface RegisterRequest extends Parsable {
    /**
     * The displayName property
     */
    displayName?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface SectionResponse extends Parsable {
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The planDrills property
     */
    planDrills?: PlanDrillResponse[] | null;
}
/**
 * Serializes information the current object
 * @param AuthUserResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthUserResponse(writer: SerializationWriter, authUserResponse: Partial<AuthUserResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!authUserResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("displayName", authUserResponse.displayName);
    writer.writeStringValue("email", authUserResponse.email);
    writer.writeStringValue("id", authUserResponse.id);
}
/**
 * Serializes information the current object
 * @param CoachRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCoachRequest(writer: SerializationWriter, coachRequest: Partial<CoachRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!coachRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("key", coachRequest.key);
    writer.writeStringValue("name", coachRequest.name);
    writer.writeStringValue("type", coachRequest.type);
}
/**
 * Serializes information the current object
 * @param CoachResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCoachResponse(writer: SerializationWriter, coachResponse: Partial<CoachResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!coachResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("key", coachResponse.key);
    writer.writeStringValue("name", coachResponse.name);
    writer.writeStringValue("type", coachResponse.type);
}
/**
 * Serializes information the current object
 * @param CreateDrillRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateDrillRequest(writer: SerializationWriter, createDrillRequest: Partial<CreateDrillRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createDrillRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("demoLink", createDrillRequest.demoLink);
    writer.writeStringValue("description", createDrillRequest.description);
    writer.writeNumberValue("drillTypeId", createDrillRequest.drillTypeId);
    writer.writeNumberValue("duration", createDrillRequest.duration);
    writer.writeStringValue("instructions", createDrillRequest.instructions);
    writer.writeStringValue("name", createDrillRequest.name);
}
/**
 * Serializes information the current object
 * @param CreatePlanDrillRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePlanDrillRequest(writer: SerializationWriter, createPlanDrillRequest: Partial<CreatePlanDrillRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPlanDrillRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("coachAssignment", createPlanDrillRequest.coachAssignment);
    writer.writeStringValue("demoLink", createPlanDrillRequest.demoLink);
    writer.writeNumberValue("displayOrder", createPlanDrillRequest.displayOrder);
    writer.writeNumberValue("drillTypeId", createPlanDrillRequest.drillTypeId);
    writer.writeNumberValue("duration", createPlanDrillRequest.duration);
    writer.writeStringValue("instructions", createPlanDrillRequest.instructions);
    writer.writeStringValue("name", createPlanDrillRequest.name);
    writer.writeNumberValue("playerCount", createPlanDrillRequest.playerCount);
    writer.writeGuidValue("sourceDrillKey", createPlanDrillRequest.sourceDrillKey);
    writer.writeGuidValue("stationGroup", createPlanDrillRequest.stationGroup);
}
/**
 * Serializes information the current object
 * @param CreatePracticePlanRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePracticePlanRequest(writer: SerializationWriter, createPracticePlanRequest: Partial<CreatePracticePlanRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPracticePlanRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", createPracticePlanRequest.description);
    writer.writeNumberValue("intendedDuration", createPracticePlanRequest.intendedDuration);
    writer.writeStringValue("location", createPracticePlanRequest.location);
    writer.writeStringValue("name", createPracticePlanRequest.name);
}
/**
 * Serializes information the current object
 * @param CreateSectionRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateSectionRequest(writer: SerializationWriter, createSectionRequest: Partial<CreateSectionRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createSectionRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("displayOrder", createSectionRequest.displayOrder);
    writer.writeStringValue("name", createSectionRequest.name);
}
/**
 * Serializes information the current object
 * @param CreateTeamRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateTeamRequest(writer: SerializationWriter, createTeamRequest: Partial<CreateTeamRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createTeamRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CoachRequest>("coaches", createTeamRequest.coaches, serializeCoachRequest);
    writer.writeStringValue("name", createTeamRequest.name);
}
/**
 * Serializes information the current object
 * @param DrillResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDrillResponse(writer: SerializationWriter, drillResponse: Partial<DrillResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!drillResponse || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", drillResponse.createdAt);
    writer.writeStringValue("demoLink", drillResponse.demoLink);
    writer.writeStringValue("description", drillResponse.description);
    writer.writeObjectValue<DrillTypeResponse>("drillType", drillResponse.drillType, serializeDrillTypeResponse);
    writer.writeNumberValue("duration", drillResponse.duration);
    writer.writeStringValue("instructions", drillResponse.instructions);
    writer.writeGuidValue("key", drillResponse.key);
    writer.writeStringValue("name", drillResponse.name);
    writer.writeStringValue("source", drillResponse.source);
    writer.writeDateValue("updatedAt", drillResponse.updatedAt);
}
/**
 * Serializes information the current object
 * @param DrillTypeResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDrillTypeResponse(writer: SerializationWriter, drillTypeResponse: Partial<DrillTypeResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!drillTypeResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("id", drillTypeResponse.id);
    writer.writeStringValue("name", drillTypeResponse.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginRequest.email);
    writer.writeStringValue("password", loginRequest.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanDrillResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanDrillResponse(writer: SerializationWriter, planDrillResponse: Partial<PlanDrillResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!planDrillResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("coachAssignment", planDrillResponse.coachAssignment);
    writer.writeStringValue("demoLink", planDrillResponse.demoLink);
    writer.writeNumberValue("displayOrder", planDrillResponse.displayOrder);
    writer.writeObjectValue<DrillTypeResponse>("drillType", planDrillResponse.drillType, serializeDrillTypeResponse);
    writer.writeNumberValue("duration", planDrillResponse.duration);
    writer.writeStringValue("instructions", planDrillResponse.instructions);
    writer.writeGuidValue("key", planDrillResponse.key);
    writer.writeStringValue("name", planDrillResponse.name);
    writer.writeNumberValue("playerCount", planDrillResponse.playerCount);
    writer.writeGuidValue("sourceDrillKey", planDrillResponse.sourceDrillKey);
    writer.writeGuidValue("stationGroup", planDrillResponse.stationGroup);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PracticePlanDetailResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePracticePlanDetailResponse(writer: SerializationWriter, practicePlanDetailResponse: Partial<PracticePlanDetailResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!practicePlanDetailResponse || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", practicePlanDetailResponse.createdAt);
    writer.writeStringValue("description", practicePlanDetailResponse.description);
    writer.writeNumberValue("intendedDuration", practicePlanDetailResponse.intendedDuration);
    writer.writeGuidValue("key", practicePlanDetailResponse.key);
    writer.writeDateValue("lastModifiedAt", practicePlanDetailResponse.lastModifiedAt);
    writer.writeStringValue("location", practicePlanDetailResponse.location);
    writer.writeStringValue("name", practicePlanDetailResponse.name);
    writer.writeCollectionOfObjectValues<SectionResponse>("sections", practicePlanDetailResponse.sections, serializeSectionResponse);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PracticePlanListResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePracticePlanListResponse(writer: SerializationWriter, practicePlanListResponse: Partial<PracticePlanListResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!practicePlanListResponse || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", practicePlanListResponse.createdAt);
    writer.writeNumberValue("intendedDuration", practicePlanListResponse.intendedDuration);
    writer.writeGuidValue("key", practicePlanListResponse.key);
    writer.writeDateValue("lastModifiedAt", practicePlanListResponse.lastModifiedAt);
    writer.writeStringValue("location", practicePlanListResponse.location);
    writer.writeStringValue("name", practicePlanListResponse.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterRequest(writer: SerializationWriter, registerRequest: Partial<RegisterRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("displayName", registerRequest.displayName);
    writer.writeStringValue("email", registerRequest.email);
    writer.writeStringValue("password", registerRequest.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SectionResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSectionResponse(writer: SerializationWriter, sectionResponse: Partial<SectionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sectionResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("displayOrder", sectionResponse.displayOrder);
    writer.writeGuidValue("key", sectionResponse.key);
    writer.writeStringValue("name", sectionResponse.name);
    writer.writeCollectionOfObjectValues<PlanDrillResponse>("planDrills", sectionResponse.planDrills, serializePlanDrillResponse);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TeamResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTeamResponse(writer: SerializationWriter, teamResponse: Partial<TeamResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!teamResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CoachResponse>("coaches", teamResponse.coaches, serializeCoachResponse);
    writer.writeGuidValue("key", teamResponse.key);
    writer.writeStringValue("name", teamResponse.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateDrillRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateDrillRequest(writer: SerializationWriter, updateDrillRequest: Partial<UpdateDrillRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateDrillRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("demoLink", updateDrillRequest.demoLink);
    writer.writeStringValue("description", updateDrillRequest.description);
    writer.writeNumberValue("drillTypeId", updateDrillRequest.drillTypeId);
    writer.writeNumberValue("duration", updateDrillRequest.duration);
    writer.writeStringValue("instructions", updateDrillRequest.instructions);
    writer.writeStringValue("name", updateDrillRequest.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdatePlanDrillRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdatePlanDrillRequest(writer: SerializationWriter, updatePlanDrillRequest: Partial<UpdatePlanDrillRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updatePlanDrillRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("coachAssignment", updatePlanDrillRequest.coachAssignment);
    writer.writeStringValue("demoLink", updatePlanDrillRequest.demoLink);
    writer.writeNumberValue("displayOrder", updatePlanDrillRequest.displayOrder);
    writer.writeNumberValue("drillTypeId", updatePlanDrillRequest.drillTypeId);
    writer.writeNumberValue("duration", updatePlanDrillRequest.duration);
    writer.writeStringValue("instructions", updatePlanDrillRequest.instructions);
    writer.writeStringValue("name", updatePlanDrillRequest.name);
    writer.writeNumberValue("playerCount", updatePlanDrillRequest.playerCount);
    writer.writeGuidValue("stationGroup", updatePlanDrillRequest.stationGroup);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdatePracticePlanRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdatePracticePlanRequest(writer: SerializationWriter, updatePracticePlanRequest: Partial<UpdatePracticePlanRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updatePracticePlanRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", updatePracticePlanRequest.description);
    writer.writeNumberValue("intendedDuration", updatePracticePlanRequest.intendedDuration);
    writer.writeStringValue("location", updatePracticePlanRequest.location);
    writer.writeStringValue("name", updatePracticePlanRequest.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateSectionRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateSectionRequest(writer: SerializationWriter, updateSectionRequest: Partial<UpdateSectionRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateSectionRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("displayOrder", updateSectionRequest.displayOrder);
    writer.writeStringValue("name", updateSectionRequest.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateTeamRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateTeamRequest(writer: SerializationWriter, updateTeamRequest: Partial<UpdateTeamRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateTeamRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CoachRequest>("coaches", updateTeamRequest.coaches, serializeCoachRequest);
    writer.writeStringValue("name", updateTeamRequest.name);
}
export interface TeamResponse extends Parsable {
    /**
     * The coaches property
     */
    coaches?: CoachResponse[] | null;
    /**
     * The key property
     */
    key?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateDrillRequest extends Parsable {
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The drillTypeId property
     */
    drillTypeId?: number | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdatePlanDrillRequest extends Parsable {
    /**
     * The coachAssignment property
     */
    coachAssignment?: string | null;
    /**
     * The demoLink property
     */
    demoLink?: string | null;
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The drillTypeId property
     */
    drillTypeId?: number | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The instructions property
     */
    instructions?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The playerCount property
     */
    playerCount?: number | null;
    /**
     * The stationGroup property
     */
    stationGroup?: Guid | null;
}
export interface UpdatePracticePlanRequest extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The intendedDuration property
     */
    intendedDuration?: number | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateSectionRequest extends Parsable {
    /**
     * The displayOrder property
     */
    displayOrder?: number | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateTeamRequest extends Parsable {
    /**
     * The coaches property
     */
    coaches?: CoachRequest[] | null;
    /**
     * The name property
     */
    name?: string | null;
}
/* tslint:enable */
/* eslint-enable */
