/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPracticePlanDetailResponseFromDiscriminatorValue, createPracticePlanListResponseFromDiscriminatorValue, serializeCreatePracticePlanRequest, serializePracticePlanDetailResponse, type CreatePracticePlanRequest, type PracticePlanDetailResponse, type PracticePlanListResponse } from '../../models/index.js';
// @ts-ignore
import { KeyItemRequestBuilderNavigationMetadata, KeyItemRequestBuilderRequestsMetadata, type KeyItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/practice-plans
 */
export interface PracticePlansRequestBuilder extends BaseRequestBuilder<PracticePlansRequestBuilder> {
    /**
     * Gets an item from the GamePlanPro.Api.api.practicePlans.item collection
     * @param keyId Unique identifier of the item
     * @returns {KeyItemRequestBuilder}
     */
     byKeyId(keyId: Guid) : KeyItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PracticePlanListResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PracticePlanListResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PracticePlanDetailResponse>}
     */
     post(body: CreatePracticePlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PracticePlanDetailResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePracticePlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PracticePlansRequestBuilderUriTemplate = "{+baseurl}/api/practice-plans";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PracticePlansRequestBuilderNavigationMetadata: Record<Exclude<keyof PracticePlansRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byKeyId: {
        requestsMetadata: KeyItemRequestBuilderRequestsMetadata,
        navigationMetadata: KeyItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["key%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PracticePlansRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PracticePlansRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPracticePlanListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: PracticePlansRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPracticePlanDetailResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePracticePlanRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
