/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCoachResponseFromDiscriminatorValue, type CoachResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/coaches/by-team
 */
export interface ByTeamRequestBuilder extends BaseRequestBuilder<ByTeamRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CoachResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CoachResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ByTeamRequestBuilderUriTemplate = "{+baseurl}/api/coaches/by-team";
/**
 * Metadata for all the requests in the request builder.
 */
export const ByTeamRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ByTeamRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createCoachResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
